site_name: NIKA
dev_addr: 127.0.0.1:9001
repo_url: https://github.com/ostis-apps/nika
edit_uri: edit/main/docs/

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js


nav:
  - Home: index.md
  - Home: index.ru.md
  - Quick Start: quick_start.md
  - Quick Start: quick_start.ru.md
  - Build Instructions:
    - Quick Start: build/quick_start.md
    - Quick Start: build/quick_start.ru.md
    - Docker: build/docker_build.md
    - Docker: build/docker_build.ru.md
    - Build System: build/build_system.md
    - Build System: build/build_system.ru.md
    - CMake Flags: build/cmake_flags.md
    - CMake Flags: build/cmake_flags.ru.md
    - Rasa classifier: build/rasa_classifier.md
    - Rasa classifier: build/rasa_classifier.ru.md
  - Development:
    - Git-workflow: dev/git-workflow.md
    - Git-workflow: dev/git-workflow.ru.md
    - Pull requests: dev/pr.md
    - Pull requests: dev/pr.ru.md
    - Codestyle: dev/codestyle.md
    - Codestyle: dev/codestyle.ru.md
  - Agents:
    - Base:
      - Message reply agent: agents/base/messageReplyAgent.md
      - Message reply agent: agents/base/messageReplyAgent.ru.md
      - Non-atomic action interpretation agent: agents/base/nonAtomicActionInterpretationAgent.md
      - Non-atomic action interpretation agent: agents/base/nonAtomicActionInterpretationAgent.ru.md
      - Standard message reply agent: agents/base/standardMessageReplyAgent.md
      - Standard message reply agent: agents/base/standardMessageReplyAgent.ru.md
      - Phrase generation agent: agents/base/phraseGenerationAgent.md
      - Phrase generation agent: agents/base/phraseGenerationAgent.ru.md
    - Classification:
      - Alternative message topic classification agent: agents/classification/alternativeMessageTopicClassificationAgent.md
      - Alternative message topic classification agent: agents/classification/alternativeMessageTopicClassificationAgent.ru.md
      - Wit.ai message topic classification agent: agents/classification/messageTopicClassificationAgent.md
      - Wit.ai message topic classification agent: agents/classification/messageTopicClassificationAgent.ru.md
      - Rasa message topic classification agent: agents/classification/rasaMessageTopicClassificationAgent.md
      - Rasa message topic classification agent: agents/classification/rasaMessageTopicClassificationAgent.ru.md
    - Auth:
      - Create Author Agent: agents/auth/createAuthorAgent.md
      - Create Author Agent: agents/auth/createAuthorAgent.ru.md
      - Create Access Tokens Agent: agents/auth/createTokensAgent.md
      - Create Access Tokens Agent: agents/auth/createTokensAgent.ru.md
    - Theme agents: 
      - Interface component color changer agent: agents/question_types/changeInterfaceColorAgent.md
      - Interface component color changer agent: agents/question_types/changeInterfaceColorAgent.ru.md
      - Weather agent: agents/question_types/weatherAgent.md
      - Weather agent: agents/question_types/weatherAgent.ru.md
      - Find word in set by first letter agent: agents/question_types/findWordInSetByFirstLetter.md
      - Find word in set by first letter agent: agents/question_types/findWordInSetByFirstLetter.ru.md
      - Requires authorization:
        - Google Calendar Event Addition Agent: agents/question_types/google/addCalendarEvent.md
        - Google Calendar Event Addition Agent: agents/question_types/google/addCalendarEvent.ru.md
        - Google Calendar Event Deleting Agent: agents/question_types/google/deleteCalendarEvent.md
        - Google Calendar Event Deleting Agent: agents/question_types/google/deleteCalendarEvent.ru.md
        - Google Calendar Event Updating Agent: agents/question_types/google/updateCalendarEvent.md
        - Google Calendar Event Updating Agent: agents/question_types/google/updateCalendarEvent.ru.md
        - Contact Creation Agent: agents/question_types/google/createContactAgent.md
        - Contact Creation Agent: agents/question_types/google/createContactAgent.ru.md
        - Send Mail Agent: agents/question_types/google/sendMailSMTP.md
        - Send Mail Agent: agents/question_types/google/sendMailSMTP.ru.md
  - Patterns:
      - Knowledge base patterns: patterns/kb-patterns.md
      - Knowledge base patterns: patterns/kb-patterns.ru.md
  - NIKA training guide: guide/training_guide.md
  - NIKA training guide: guide/training_guide.ru.md
  - Subsystems:
     - scl-machine: subsystems/scl-machine.md
     - scl-machine: subsystems/scl-machine.ru.md
  - Thirdparty: thirdparty.md
  - Thirdparty: thirdparty.ru.md
  - License: license.md
  - Changelog: changelog.md

plugins:
   - search:
      lang: en
      separator: '[\s\-\.]+'
   - i18n:
      default_language: en
      languages:
        en: English
        ru: Русский
      no_translation:
        ru: "Эта страница не переведена на русский язык"
        en: "This page isn't translated to English"
      translate_nav:
        ru:
          Home: "Главная"
          Quick Start: "Быстрый старт"
          Build Instructions: "Инструкции сборки"
          Build System: "Система сборки"
          CMake Flags: "Флаги CMake"
          Development: "Разработка"
          Agents: "Агенты"
          Patterns: "Шаблоны"
          Knowledge base patterns: "Шаблоны для базы знаний"
          Base: "Базовые"
          Classification: "Классификация"
          Message reply agent: "Агент ответа на сообщение"
          Non-atomic action interpretation agent: "Агент интерпретации неатомарных действий"
          Standard message reply agent: "Агент генерации ответа на сообщение"
          Phrase generation agent: "Агент генерации фраз"
          Alternative message topic classification agent: "Альтернативный агент классификации темы сообщения"
          Wit.ai message topic classification agent: "Агент классификации темы сообщения (Wit.ai)"
          Rasa message topic classification agent: "Агент классификации темы сообщения (Rasa)"
          Auth: "Авторизация"
          Create Access Tokens Agent: "Агент создания токенов доступа"
          Create Author Agent: "Агент создания автора"
          Theme agents: "Тематические агенты"
          Interface component color changer agent: "Агент смены цвета компонента интерфейса"
          Weather agent: "Агент прогноза погоды"
          Find word in set by first letter agent: "Агент поиска слова по первой букве"
          Requires authorization: "Требуют авторизации"
          Contact Creation Agent: "Агент создания контакта"
          Google Calendar Event Addition Agent: "Агент добавления события в гугл календарь"
          Send Mail Agent: "Агент отправки сообщения по почте"
          Google Calendar Event Updating Agent: "Агент обновления события в гугл календаре"
          Google Calendar Event Deleting Agent: "Агент удаления события из гугл календаря"
          Subsystems: "Подсистемы"
          License: "Лицензия"
          Changelog: "Список изменений"
          Thirdparty: "Сторонние компоненты"

theme: 
  name: material
  favicon: ostis-logo.png
  logo: ostis-logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.tabs.link
    - content.code.copy

extra:
  alternate:
    - name: "Home"
      link: ""
      lang: en
    - name: "Главная"
      link: index.ru
      lang: ru

markdown_extensions:
  - admonition
  - codehilite
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences